# Generated by Django 6.0.4 on 2026-05-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('comment_reply', 'Comment Reply'), ('game_update', 'Game Update'), ('announcement', 'Announcement')], max_length=30),
        ),
    ]
