# Generated by Django 6.0.4 on 2026-05-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_type'),
        ('notifications', 'notifications_0004_developerannouncement'),
    ]

    operations = [
    ]
