# Generated by Django 6.0.3 on 2026-05-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
        ('commerce', '0004_paymentmethod_stripecustomer'),
    ]

    operations = [
    ]
