# Generated by Django 6.0.3 on 2026-05-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_developerprofile_id_alter_followdeveloper_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
