# Generated by Django 6.0.4 on 2026-04-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher', models.CharField(max_length=150)),
                ('release_year', models.PositiveIntegerField()),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('PS4', 'PS4'), ('PS5', 'PS5'), ('XBOX', 'Xbox'), ('SWITCH', 'Nintendo Switch'), ('WEB', 'Web Browser')], default='PC', max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='games/covers/')),
                ('play_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
