# Generated by Django 6.0.4 on 2026-04-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_file',
            field=models.FileField(blank=True, null=True, upload_to='games/files/'),
        ),
    ]
