# Generated by Django 6.0.4 on 2026-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_file',
        ),
        migrations.AddField(
            model_name='game',
            name='game_zip',
            field=models.FileField(blank=True, null=True, upload_to='games/zips/'),
        ),
        migrations.AddField(
            model_name='game',
            name='launch_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
