# Generated by Django 6.0.3 on 2026-04-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_game_file_game_game_zip_game_launch_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='game_media/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='game_versions/')),
                ('entry_point', models.CharField(max_length=255)),
                ('changelog', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='trending_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='temp-slug', unique=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='games_game_title_b7a574_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['avg_rating'], name='games_game_avg_rat_4d5f11_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['price'], name='games_game_price_eb935e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['trending_score'], name='games_game_trendin_b8ca00_idx'),
        ),
        migrations.AddField(
            model_name='gamemedia',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameversion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.genre'),
        ),
    ]
