# Generated by Django 4.2.29 on 2026-05-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamemedia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='entry_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='file',
            field=models.FileField(blank=True, upload_to='game_versions/'),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='version_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
