# Generated by Django 6.0.4 on 2026-05-02 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
        ('games', '0008_gamekey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamekey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='gamekey',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamekey',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.order'),
        ),
        migrations.AlterField(
            model_name='gamekey',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
